FROM tomcat
WORKDIR /usr/local/tomcat/webapps
COPY ./FeedbackApp/target/feedback-app-0.0.1-SNAPSHOT.jar /usr/local/tomcat/webapps/
EXPOSE 8080
CMD  [ "java" , "-jar" , "feedback-app-0.0.1-SNAPSHOT.jar" ]